using System;

namespace ProjectEulerSolutions.Solutions
{
    public static class Problem2
    {
        /*Each new term in the Fibonacci sequence is generated by adding the previous two terms.By starting with 1 and 2, the first 10 terms will be:

        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

        By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/

        public static int Solve(bool output = false)
        {
            int result = 0;
            int sum = 0;
            // Seed value
            int[] seed = new int[2] { 1, 1 };

            // Loop until the sum reaches 4000000
            while (sum<=4000000)
            {
                // Sum the previous two terms
                sum = seed[0] + seed[1]; 
                // Write the sum and the previous term back to the seed array
                seed[0] = seed[1];
                seed[1] = sum;

                if (sum % 2 == 0)
                {
                    // Add to result if the new number in the sequence is even
                    result += sum;
                    if (output) Console.WriteLine($"{result} {sum}");
                }
            }

            return (result);
        }

    }
}
